#!/bin/bash

PROJDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

NETID=$(cat $PROJDIR/.netidtemp)
DOMAIN=utdallas.edu

#command line arguments
CONFIGPATH=$PROJDIR/config
CONFIG=$CONFIGPATH/$(cat $PROJDIR/.configtemp)

PROJDIRSCRIPT='$(echo $AOSMEROOT)'
REMOTELOGS=$PROJDIRSCRIPT/logs

n=0
host=dc01
cat $CONFIG | sed -e "s/#.*//" | sed -e "/^\s*$/d" |
(
	read i
	nodes=$(echo $i | cut -f1 -d" ")
		
	while IFS='' read -r line || [[ -n "$line" ]];
	do
		host=$(echo $line | awk '{print $2}')

		echo Cleaning $host

        # having two seems to help
		ssh -n $NETID@$host.$DOMAIN "pkill -u $NETID java" &
		ssh -n $NETID@$host.$DOMAIN "pkill -u $NETID java" &

		n=$(($n + 1))
		if [ $n -ge $nodes ];then
			break
		fi
	done
)

echo "Cleanup complete"
