#!/bin/bash

PROJDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJDIRFIND='$(find ~ -name '\'Aos-Mutual-Exclusion\'' | head -1)'
PROJDIRSCRIPT='$(echo $AOSMEROOT)'

NETID=$1
DOMAIN=utdallas.edu

echo $1 > $PROJDIR/.netidtemp

#command line arguments
MCONFIGPATH=$PROJDIR/mconfig
MCONFIG=$MCONFIGPATH/$(basename $2)
OUTPUT=$3

echo $(basename $2) > $PROJDIR/.mconfigtemp

# commented this out since it's unused and rev is a problem on MinGW
#config_file_name=$(echo $CONFIG | rev | cut -f1 -d"/" |rev | cut -f1 -d ".")
#echo $config_file_name
#extract lines from config file

COLS=$(stty size | cut -f2 -d" ")

COUNT=$(grep . $MCONFIG | wc -l)
i=1
while IFS='' read -r line || [[ -n "$line" ]];
do
    if [ -n "$line" ]; then
        cfile=$(echo $line | cut -d" " -f1)
        runs=$(echo $line | cut -d" " -f2)
        greedy=$(echo $line | cut -d" " -f3)
        
        if [ -z "$greedy" ]; then
            greedy=false
        fi
        
        j=1
        while [ $j -le $runs ]; do
            echo Processing $cfile '('$i '/' $COUNT')' run $j of $runs '('greedy = $greedy')'
            bash launcher $(cat .netidtemp) $cfile $greedy
            bash progress $OUTPUT $COLS
            j=$(($j+1))
        done
        
        i=$(($i + 1))
    fi
done < $MCONFIG
