#!/bin/bash

PROJDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

NETID=$(cat $PROJDIR/.netidtemp)
DOMAIN=utdallas.edu

#command line arguments
CONFIGPATH=$PROJDIR/config
CONFIG=$CONFIGPATH/$(cat $PROJDIR/.configtemp)

PROJDIRSCRIPT='$(echo $AOSMEROOT)'
REMOTELOGS=$PROJDIRSCRIPT/logs
REMOTEOUT=$PROJDIRSCRIPT/out

n=0
host=dc01
cat $CONFIG | sed -e "s/#.*//" | sed -e "/^\s*$/d" |
(
	read i
	nodes=$(echo $i | cut -f1 -d" ")
		
	while IFS='' read -r line || [[ -n "$line" ]];
	do
		host=$(echo $line | awk '{print $2}')

		echo Checking $host for Java processes:

		ssh -n $NETID@$host.$DOMAIN "ps -fu "'$USER'" | grep java | grep -v grep | grep -v bash"

		n=$(($n + 1))
		if [ $n -ge $nodes ];then
			break
		fi
	done
)
