#!/bin/bash

#command line arguments
CLASSPATH=aosme/
CLASSFILE=Kernel
CLASSAPPFILE=Application
CONFIGPATH=/home/012/s/sx/sxn164530/aosme/config
CONFIG=$1

echo -e "">debug.txt

config_file_name=$(echo $CONFIG | rev | cut -f1 -d"/" |rev | cut -f1 -d ".")

echo $config_file_name
#extract lines from config file

sed -e "s/#.*//" $CONFIG | sed -e "/^\s*$/d" >temp

echo >>temp

CONFIGPATH=/home/012/s/sx/sxn164530/temp

node_count=0
inter_request_delay=0
critical_section_time=0
num_requests=0
host_list=()
port_list=()
parent_list=()
counter=0
current_line=1

while read line;
do
	#turn all spaces to single line
	line=$(echo $line | tr -s ' ')
	if [ $current_line -eq 1 ]; then
		line1=($line)
		node_count=$(echo $line | cut -f1 -d" ")
		inter_request_delay=$(echo $line | cut -f2 -d" ")
		critical_section_time=$(echo $line | cut -f3 -d" ")
		num_requests=$(echo $line | cut -f4 -d" ")	
	else
		stringarray=($line)
		
		port_id=${stringarray[2]}
		port_list+=($port_id)
		
		host=${stringarray[1]}
		host_list+=($host)
	
		parent=${stringarray[3]}
		parent_list+=($parent)
		
	fi
	let current_line+=1


done < temp

echo ${host_list[0]}
counter=0
javac $CLASSPATH$CLASSFILE.java

while [ $counter -lt $node_count ]
do
	
 ssh ${host_list[$counter]} java $CLASSPATH$CLASSFILE $counter ${host_list[$counter]} ${port_list[$counter]} ${parent_list[$counter]} $CONFIGPATH $node_count &
#ssh $host java $CLASSPATH$CLASSAPPFILE $inter_request_delay $critical_section_time &


let counter+=1
	
done
	
